LXDのコンテナのGPU情報をもとにGPU割当
KeioAIConsortium/iris pull request #6
Opened 2021-02-24 04:40 UTC by yuziroppe

# WHAT

プロセスが走っていない、かつ、ユーザに割り当てた量が最少のGPUを提供する

# WHY

ユーザに割り当てたGPUの競合を減らしたい

2021-02-24 05:38 UTC, yuziroppe commented
tippy上でテスト済み, GPUに対するコンテナ数の取得, 割り当てられたコンテナが最少のGPUを優先的に割り当てられることが確認済み

2021-03-02 09:22 UTC, nkpoid requested changes

2021-03-02 09:22 UTC, nkpoid commented on main.go
> +		containers, err := c.GetContainers()
この程度の薄いプログラムなら現時点で問題になることは無いとは思うけど，とはいえここの，いわゆるview部分にロジックをあまり書きたくないので隠蔽するべきだと思う

2021-03-02 09:22 UTC, nkpoid commented on main.go
> +	for k, v := range availableGpuLookup {
変数名わかりやすくしたほうがいいかも

2021-06-27 09:06 UTC, yuziroppe commented
遅くなりましたが修正箇所直しました〜

- 一度だけ初期化すれば良い変数はグローバル変数にしました
- 変数名をわかりやすくしました

基本的に状態を保持しない(orGPUデバイス情報、unixsocket周りは一度初期化したら変える必要がない)ためmutexなどで実装はしておりません。

2021-06-28 23:52 UTC, 190ikp approved these changes
LGTM 👍

2021-06-29 02:35 UTC, yuziroppe commented
@190ikp 来週の水曜日にメモリ増設するときにirisもアップデートしようと思う

2021-07-05 12:59 UTC, nkpoid requested changes
色々コメントした，あと可能な範囲でユニットテスト書きたいかも(書ける？)

2021-07-05 12:59 UTC, nkpoid commented on main.go
> +func initClusterState(containers []api.Container) ClusterState {
ポインタの配列を受け取りたいです

2021-07-05 12:59 UTC, nkpoid commented on main.go
> +func initClusterState(containers []api.Container) ClusterState {
数が多いので全てのコメントはしないですが，api.Container含めプリミティブ以外の値を受け渡すときにはコピーコストが気になるのでポインタ使ってほしいです

2021-07-05 12:59 UTC, nkpoid commented on main.go
> +	reg, _ := regexp.Compile("^jupyterhub-singleuser-instance")
`regexp.MustCompile`を使ってconstにしてほしいです

2021-07-05 12:59 UTC, nkpoid commented on main.go
> +	// MEMO: assign the gpu whose assosiated containers' number is the smallest even through the gpu has working processes
assosiated→associated

2021-07-05 12:59 UTC, nkpoid commented on main.go
> +func getAvailableGpuPciAddress(containers []api.Container, devices []nvml.Device) (string, error) {
エラーハンドリングで全てプログラム終了する(`log.Fatal`のであればerror返さないでよいのでは？)

2021-07-05 12:59 UTC, nkpoid commented on main.go
>  func jsonifyPrettyForLog(value interface{}) string {
使ってないので消しちゃいましょう

2021-07-05 12:59 UTC, nkpoid commented on main.go
> +		w.WriteHeader(http.StatusInternalServerError)
log.Fatal系を呼んだ段階でその後の処理実行されないですけど意図されていますか？

2021-07-05 14:43 UTC, yuziroppe commented on main.go
> +		w.WriteHeader(http.StatusInternalServerError)
これは完全に調べずに書いてしまった、申し訳ない

2021-07-05 14:44 UTC, yuziroppe commented on main.go
>  func jsonifyPrettyForLog(value interface{}) string {
これグローバル変数として使っています、main関数と、httpのエンドポイントで

2021-07-05 14:58 UTC, yuziroppe commented on main.go
>  func jsonifyPrettyForLog(value interface{}) string {
ただ、グローバルとして扱いたい変数をmain内で代入する時に、こんな書き方になっちゃったけど良い書き方がわからない

2021-07-05 22:35 UTC, nkpoid commented on main.go
>  func jsonifyPrettyForLog(value interface{}) string {
これgithubが出すところが悪いな，jsonifyPrettyForLogのこと言ってました(直接の変更点じゃないから分かりづらい表示になってそう)

2021-07-05 22:39 UTC, nkpoid commented on main.go
> +func initClusterState(containers []api.Container) ClusterState {
4e47a2f 意図していたのは，`配列のポインタ`ではなく`ポインタの配列`です(伝わりますか？)

2021-07-05 22:40 UTC, nkpoid commented on main.go
> +func initClusterState(containers []api.Container) ClusterState {
上の修正だと結局値のコピーが発生していて全く意味をなしてない変更になってます><

2021-07-05 22:43 UTC, nkpoid commented on main.go
> +func initClusterState(containers []api.Container) ClusterState {
書き方としては，
`*[]api.Container` ではなく `[]*api.Container`となります

2021-07-05 22:46 UTC, nkpoid commented
あと可能なら修正コミットは話題ごとに分割していただけるとre-reviewが楽です(まぁ気持ちは分かるので可能な範囲で…)

2021-07-06 07:21 UTC, yuziroppe commented on main.go
> +func initClusterState(containers []api.Container) ClusterState {
配列のポインタじゃなくて、ポインタの配列、意図が伝わりました。
直します。これ、配列のポインタだと、要素も勝手に参照してくれると自分が誤解していました。(開始アドレス持っていれば、勝手に他のポインタもアクセスできるみたいに)

2021-07-06 07:27 UTC, yuziroppe commented
これ、mustcompileで初期化したときconstにできない。なぜなら基本型以外、constにできないから

2021-07-06 07:30 UTC, yuziroppe commented
https://golangbyexample.com/const-struct-go
https://blog.golang.org/constants

2021-07-06 07:30 UTC, yuziroppe commented on main.go
>  func jsonifyPrettyForLog(value interface{}) string {
了解しました

2021-07-06 08:09 UTC, nkpoid commented
あーその制約わすれてた、あざす

2021-07-06 22:47 UTC, nkpoid approved these changes
一旦LGTM

2021-07-06 22:50 UTC, nkpoid commented on main.go
> +		containers = append(containers, &c)
あ，ごめんここだけ直してほしい
[こういう](https://husni.dev/beware-of-implicit-memory-aliasing-in-go-foor-loop/)挙動を示してしまうので，index accessするか，もしくはこの行の前に`c := c`を書いて変数束縛してほしい

2021-07-06 23:19 UTC, yuziroppe commented
めちゃくちゃ重大な指摘ありがとう

2021-07-06 23:24 UTC, yuziroppe commented
レビューありがとう、マージしちゃいます

2021-07-06 23:25 UTC, nkpoid approved these changes

2021-07-06 23:29 UTC, merged